name: compliance-check 

on:
  repository_dispatch:
    types: [org-workflow-bot]  # <-- requirement to trigger central workflows 
    
jobs:
  register-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: svanboxel/organization-workflow@1.3.0
      with:
        id: $
        callback_url: $
        sha: $
        run_id: $
        name: $ # Default: name of workflow. This name is shown with the check, but can be changed.

# ... the checks and jobs that need to happen in your workflow.
    - name: repo name check
      shell: bash
      run: |
        REPO_NAME=cut -d "/" -f2 <<< "$GITHUB_REPOSITORY"
        if [[ $REPO_NAME =~ ^[0-9]{6,6}-[A-Za-z0-9]{1,3}-[A-Za-z0-9]{1,}$ ]]; then
          echo "matched"
        else
          echo "not matched"
        fi
 
